### ISSUE TITLE
Run: docker-compose up

### ISSUE THREAD

**Issue by CHN-WolF** [mithrand0/reactive-drop-linux-server#1]
=> ERROR [internal] load metadata for ghcr.io/mithrand0/linux-proton-steam:latest
![QQ图片20221208142445](https://user-images.githubusercontent.com/17807433/206373520-869faaf1-162e-4741-ac38-8623b298690f.png)

**Comment by mithrand0** [comment]
> GitHub Packages (used to store the image) are not allowing anonymous access. You will have to authenticate with your GitHub credentials or PAT.

If you log in with your GitHub credentials before building, it should work.

**Comment by mithrand0** [comment]
Related to #2
